# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9361e320e706e7ce9ce21cfe369c62e21cc8329667e8f0f169ad6fe77e2eabe723589506ff114ef12e7b1c0370f26780f04127ec2b89d8859089897f0daea20

test:
  secret_key_base: c8175e1ef1d496144fc13b72948976f7eb120cfd602ba96a04bb96a32167943b46370975e6882684f9640d3a617481f51545fd86b9f6443e1058d103b2529c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
